GET https://boilertplate-ecommerce.herokuapp.com/api/v1/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNmJiODFmZDFjMGNhMDAyMTE1OTFhMiIsImlhdCI6MTYxNzY3MjQyMiwiZXhwIjoxNjE3NzU4ODIyfQ.bqaKxdLn5X8rtVqGMvDx1V1RKnctXQu7cAAoVXpUVD4

### get by id
GET http://localhost:4000/api/v1/users/604518a2e0792d275e8b3eff HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNTAxNWM1MDZiOGQ1MTJlNTAwMzA0NSIsImlhdCI6MTYxNTk0NzA5NywiZXhwIjoxNjE2MDMzNDk3fQ.LhBQBvaTMgjcoU9wEFwaDwM3MzrgaxtNIO2OhWWeRLU

### Creacion Registro
POST https://boilertplate-ecommerce.herokuapp.com/api/v1/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Eleyn",
  "lastName": "Kennedy",
  "email": "eleyn@anjrot.cl",
  "password": "123456"
}

### Login
POST http://localhost:4000/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "123456"
}
### Login heroku
POST https://boilertplate-ecommerce.herokuapp.com/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "admin@anjrot.com",
  "password": "123456"
}

###update
PUT http://localhost:4000/api/v1/users/605e9088bc58da8f792b672c HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNWU5MDg4YmM1OGRhOGY3OTJiNjcyYyIsImlhdCI6MTYxNjgxMDEyMCwiZXhwIjoxNjE2ODk2NTIwfQ.oMA6qhapOi7sKzSCJ5y8P4IQAVwbIDe1-TcsWFkDzpU

{
  "name": "actualizado desde is owner"
}

### delete
DELETE http://localhost:4000/api/v1/users/605e9088bc58da8f792b672c HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNWU5MDg4YmM1OGRhOGY3OTJiNjcyYyIsImlhdCI6MTYxNjgxMDEyMCwiZXhwIjoxNjE2ODk2NTIwfQ.oMA6qhapOi7sKzSCJ5y8P4IQAVwbIDe1-TcsWFkDzpU

## eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNWU5MDg4YmM1OGRhOGY3OTJiNjcyYyIsImlhdCI6MTYxNjgxMDEyMCwiZXhwIjoxNjE2ODk2NTIwfQ.oMA6qhapOi7sKzSCJ5y8P4IQAVwbIDe1-TcsWFkDzpU